# Generated by Django 6.1.1 on 2026-10-03 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabSettingsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('version', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConcentrationConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_volume', models.DecimalField(decimal_places=2, max_digits=4)),
                ('stock_concentration', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lab_setting_configuration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='concentration_config', to='api.labsettingsconfig')),
            ],
        ),
        migrations.CreateModel(
            name='CoagulationConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flash_mixing_speed', models.PositiveIntegerField()),
                ('flash_mixing_duration', models.PositiveIntegerField()),
                ('coagulant_dispense_timing', models.PositiveIntegerField()),
                ('slow_mixing_configuration', models.JSONField(default=dict)),
                ('settling_duration', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lab_setting_configuration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coagulation_config', to='api.labsettingsconfig')),
            ],
        ),
        migrations.CreateModel(
            name='RawWaterAnalysisConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stirring_speed', models.PositiveIntegerField()),
                ('stirring_duration', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lab_settings_configuration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_config', to='api.labsettingsconfig')),
            ],
        ),
        migrations.CreateModel(
            name='RawWaterSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_ref_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('lab_settings_configuration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_water_samples', to='api.labsettingsconfig')),
            ],
        ),
        migrations.CreateModel(
            name='RawWaterQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turbidity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pH', models.DecimalField(decimal_places=2, max_digits=4)),
                ('conductivity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('alkalinity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('raw_water_sample', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='raw_water_quality', to='api.rawwatersample')),
            ],
        ),
        migrations.CreateModel(
            name='ModelRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_dosage', models.DecimalField(decimal_places=2, max_digits=8)),
                ('volume_to_dispense', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lab_settings_configuration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recommendations', to='api.labsettingsconfig')),
                ('raw_water_sample', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation', to='api.rawwatersample')),
            ],
        ),
        migrations.CreateModel(
            name='ValidationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_status', models.CharField(max_length=100)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('lab_settings_configuration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='validation_sessions', to='api.labsettingsconfig')),
                ('raw_water_sample', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='validation_session', to='api.rawwatersample')),
            ],
        ),
        migrations.CreateModel(
            name='ValidationTrial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_no', models.PositiveIntegerField()),
                ('applied_dosage', models.DecimalField(decimal_places=2, max_digits=8)),
                ('applied_volume', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(max_length=50)),
                ('validation_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_trials', to='api.validationsession')),
            ],
        ),
        migrations.AddField(
            model_name='validationsession',
            name='final_trial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_validation_sessions', to='api.validationtrial'),
        ),
        migrations.CreateModel(
            name='ResultingWaterQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turbidity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pH', models.DecimalField(decimal_places=2, max_digits=4)),
                ('conductivity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('alkalinity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('validation_trial', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resulting_water_quality', to='api.validationtrial')),
            ],
        ),
        migrations.AddConstraint(
            model_name='validationtrial',
            constraint=models.UniqueConstraint(fields=('validation_session', 'trial_no'), name='unique_trial_number_per_session'),
        ),
    ]
