# Generated by Django 6.1.1 on 2026-10-09 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawwatersample',
            name='analysis_request_id',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
